name: Performance for Pull Request
on:
  pull_request_target:
    branches: [ master ]

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Run benchmark
        run: go test -bench '.' -benchmem ./... | tee output.txt
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: output.txt
          benchmark-data-dir-path: benchmark-monitoring
          save-data-file: false
          fail-on-alert: true
          alert-threshold: '110%'
          fail-threshold: '200%'
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: gh-pages
          # Enable alert commit comment
          comment-on-alert: true
          comment-always: true